In [11]:
#Problem : 1
#Create a null vector of size 10 but the fifth value which is 1.

import numpy as np
x = np.zeros(10)
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [12]:
#Problem : 2
#2. Create a vector with values ranging from 10 to 49.

import numpy as np
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
#Problem : 3
#Create a 3x3 matrix with values ranging from 0 to 8

import numpy as np
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
#Problem : 4
#Find indices of non-zero elements from [1,2,0,0,4,0]

nums = np.array([1,2,0,0,4,0])
print("Original array: ", nums)
result = np.where(nums !=0)[0]
print("Non-Zero Element Indices is:",result)

Original array:  [1 2 0 0 4 0]
Non-Zero Element Indices is: [0 1 4]


In [9]:
#Problem : 5
#Create a 10x10 array with random values and find the minimum and maximum values.

x = np.random.random((10,10))
print(x)
xmin,xmax = x.min(), x.max()
print("Minimum Value is: ",xmin)
print("Maximum Value is: ",xmax)

[[0.96587518 0.00296321 0.08819563 0.49129105 0.90984286 0.07551262
  0.95018473 0.85638746 0.28925261 0.45711562]
 [0.36297486 0.32278439 0.92579639 0.75782362 0.07236863 0.05530242
  0.3776014  0.76671658 0.21485446 0.08025376]
 [0.47945193 0.2385953  0.87853868 0.5245969  0.3089557  0.73380762
  0.9237408  0.27260225 0.13321053 0.76725808]
 [0.74535933 0.12937876 0.21856143 0.02671981 0.3342093  0.28651325
  0.24407231 0.36677817 0.19102099 0.44700039]
 [0.21496626 0.48510353 0.65861009 0.07273828 0.72698626 0.96392818
  0.84933612 0.29777554 0.94366223 0.13196964]
 [0.44743943 0.93429553 0.0215881  0.67555061 0.70281456 0.11180801
  0.86554142 0.53310199 0.58682192 0.21639838]
 [0.75271495 0.81627743 0.61831913 0.19663594 0.03163602 0.34641741
  0.78501221 0.78561058 0.03456652 0.31109679]
 [0.57204757 0.13652046 0.47726085 0.19039662 0.78084169 0.63718505
  0.47403315 0.06591055 0.26997019 0.60702541]
 [0.16999118 0.37968763 0.17140088 0.33163955 0.30606334 0.44153754
  0.8446879 

In [15]:
#Problem : 6
#Create a random vector of size 30 and find the mean value.

z = np.random.random((30))
print(z)
m = z.mean()
print("Mean Value is: ",m)

[0.52789724 0.0559434  0.67442143 0.24389689 0.28653425 0.36226977
 0.57373838 0.69109498 0.25301142 0.72146769 0.20604972 0.15410489
 0.8763577  0.06868525 0.41964671 0.10461251 0.71027865 0.80749758
 0.38757112 0.78051619 0.08900343 0.73155725 0.4834261  0.29414951
 0.89106964 0.62332626 0.6327474  0.09103831 0.14792474 0.22930619]
Mean Value is:  0.4373048199757783
